baseURL = 'https://mugcat.fr/'
languageCode = 'fr-fr'
title = 'Mugcat'
theme = "mugcat"
author="Florian Dupeyron"

sectionMenuPages="main"

[menu]
[[menu.main]]
  name    = 'A propos'
  pageRef = '/about'
  params  = {icon    = "user-o"}
  weight  = 10

[[menu.main]]
  name    = "Posts"
  pageRef = "/posts"
  params  = {icon = "book" }
  weight  = 20


[[menu.main]]
  name    = "Projets"
  pageRef = "/projects"
  params  = {icon = "microchip"}
  weight  = 30
