baseURL = 'https://mugcat.fr'
title = 'Mugcat'
theme = "mugcat"
sectionMenuPages="main"

defaultContentLanguage="fr"
defaultContentLanguageInSubdir=true

[markup.goldmark.renderer]
 unsafe = true

[markup.highlight]
linenos=true
noClasses=false


[minify]
minifyOutput = true


[languages]
[languages.fr]
	[languages.fr.params.author]
	name="Florian Dupeyron"

	[languages.fr.menu]
	[[languages.fr.menu.main]]
	  name    = 'A propos'
	  pageRef = '/about'
	  params  = {icon    = "user-o"}
	  weight  = 10


	#[[languages.fr.menu.main]]
	#  name    = "Posts"
	#  pageRef = "/posts"
	#  params  = {icon = "book" }
	#  weight  = 20


	[[languages.fr.menu.main]]
	  name    = "Projets"
	  pageRef = "/projects"
	  params  = {icon = "microchip"}
	  weight  = 30


[languages.en]
	[languages.en.params.author]
	name="Florian Dupeyron"

	[[languages.en.menu.main]]
	  name    = 'About'
	  pageRef = '/about'
	  params  = {icon    = "user-o"}
	  weight  = 10

	#[[languages.en.menu.main]]
	#  name    = "Posts"
	#  pageRef = "/posts"
	#  params  = {icon = "book" }
	#  weight  = 20


	[[languages.en.menu.main]]
	  name    = "Projects"
	  pageRef = "/projects"
	  params  = {icon = "microchip"}
	  weight  = 30
