baseURL = 'https://mugcat.fr/'
languageCode = 'fr-fr'
title = 'Mugcat'
theme = "mugcat"
author="Florian Dupeyron"

sectionMenuPages="main"

[menu]
[[menu.main]]
  name    = 'A propos'
  pageRef = '/about'
  params  = {icon    = "user-o"}
  weight  = 10
