name: Deploy Hugo site to Pages
# https://gohugo.io/host-and-deploy/host-on-github-pages/

on:
  push:
    branches:
      - task/2 # TODO change to master

  # Manual trigger
  workflow_dispatch:

# Allow deployment to github pages
permissions:
  contents: read
  pages: write
  id-token: write

# Do not break currently running jobs to avoid to break website
concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.148.2
      HUGO_SHA1: "63ed848b481e08a77e0e7211a463f915eeec05f8"
      HUGO_ENVIRONMENT: production
      TZ: Europe/Paris

    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          echo "${HUGO_SHA1} ${{ runner.temp }}/hugo.deb" | sha1sum -c -
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Cache restore
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            $ {{ runner.temp }}/hugo_cache
          key: hugo-${{ github.run_id }}
          restore-keys:
            hugo-

      - name: Configure git
        run: git config core.quotepath false

      - name: Build with hugo
        run: |
          cd hugo
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/" \
            --cacheDir "${{ runner.temp }}/hugo_cache"

      - name: Cache save
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ runner.temp }}/hugo_cache
          key: ${{steps.cache-restore.outputs.cache-primary-key }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./hugo/public

  # Deployment job
  deploy: 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4
